# Header
menu:
  home: /
rss: /atom.xml
banner: images/andrew-ridley-jR4Zf-riEjI-unsplash.jpg

# Content
excerpt_link: Đọc tiếp →
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- tag
- tagcloud
- category
- archive

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: G-1CPE7Q03HT
gauges_analytics:
twitter:
google_plus:
fb_admins:
fb_app_id:
